export const DPP_ANNEX_I = [
  { key: "product_description", label: "Product Information" },
  { key: "composition", label: "Materials & Composition" },
  { key: "use_phase", label: "Use & Care Instructions" },
  { key: "brand_info", label: "Brand & Manufacturer" },
  { key: "social_impact", label: "Social Responsibility" },
  { key: "animal_welfare", label: "Animal Welfare" },
  { key: "environmental_impact", label: "Environmental Impact" },
  { key: "circularity", label: "Circularity & Recyclability" },
  { key: "health_safety", label: "Health & Safety" },
  { key: "digital_identity", label: "Digital Identity (DID)" },
  { key: "quantity_info", label: "Quantity Information" },
  { key: "cost_info", label: "Cost Transparency" },
  { key: "transport", label: "Transport & Logistics" },
  { key: "documentation", label: "Documents & Certificates" },
  { key: "supply_chain", label: "Supply Chain Transparency" },
  { key: "end_of_life", label: "End-of-life Instructions" },
];
